dataset:
  name: "isaac"
  base_dir: /home/docker_user/BeyondBareQueries/IsaacSimData
  sequence: "warehouse"
  start: 0
  end: -1
  stride: 2
  desired_height: 720
  desired_width: 1280
  camera_params:
    image_height: 720
    image_width: 1280
    fx: 800.0
    fy: 2354.356853615721
    cx: 639.5
    cy: 359.5
    png_depth_scale: 6553.5 # for depth image in png format
    crop_edge: 0
  relative_pose: False
  device: "cpu"

nodes_constructor:
  mask_generator:
    model: "MobileSAM"
    weights_path: "/home/docker_user/bbq_weights/mobilesamv2/weight"
  dino_generator:
    model: "dinov2_vits14_reg_lc"
    load_size: 448
    stride: 7
    facet: "value"
    num_patches_h: 63
    num_patches_w: 113
  detections_assembler:
    mask_conf_threshold: 0.95
    mask_area_threshold: 500
    max_bbox_area_ratio: 0.75
    min_points_threshold: 150
    downsample_voxel_size: 0.025
    dbscan_remove_noise: True
    dbscan_eps: 0.05
    dbscan_min_points: 10
    image_area: 921600 # desired_height * desired_width
  objects_associator:
    merge_det_obj_spatial_sim_thresh: 0.01
    merge_det_obj_visual_sim_thresh: 0.5
    downsample_voxel_size: 0.025
    merge_interval: 20
    merge_objects_overlap_thresh: 0.7
    merge_objects_visual_sim_thresh: 0.4
  projector:
    num_views: 5
    top_k: 1
    desired_height: 720
    desired_width: 1280
  postprocessing:
    obj_min_points: 150
    obj_min_detections: 3
  output_path: "/home/docker_user/BeyondBareQueries/output/scenes"
  output_name_nodes: "isaac_warehouse.json"
  output_name_objects: "isaac_warehouse_objects.pkl.gz"
